# Generated by Django 6.0.4 on 2026-04-09 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(db_column='id_area', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'areas_trabajo',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id_candidato', models.AutoField(db_column='id_candidato', primary_key=True, serialize=False)),
                ('nidentificacion', models.CharField(db_column='numero_identificacion', max_length=100, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('telefono', models.CharField(max_length=50)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('disponibilidad', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('aspiracion_salarial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('url_documento_id', models.TextField(blank=True, null=True)),
                ('url_referencias', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'candidatos',
            },
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id_entrevista', models.AutoField(db_column='id_entrevista', primary_key=True, serialize=False)),
                ('fecha_entrevista', models.DateTimeField()),
                ('observaciones', models.TextField()),
                ('eligibilidad', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(db_column='candidato_id', on_delete=django.db.models.deletion.CASCADE, to='talento.candidato')),
                ('entrevistador', models.ForeignKey(db_column='entrevistador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entrevistas',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(db_column='id_especialidad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.CASCADE, to='talento.area')),
            ],
            options={
                'db_table': 'especialidades',
            },
        ),
        migrations.AddField(
            model_name='candidato',
            name='especialidades',
            field=models.ManyToManyField(db_table='candidato_especialidad', to='talento.especialidad'),
        ),
    ]
