# Generated by Django 6.0.4 on 2026-04-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='pais',
            field=models.CharField(choices=[('', 'Seleccionar País'), ('Venezuela', 'Venezuela')], default='Venezuela', max_length=100),
        ),
    ]
