# Generated by Django 6.0.4 on 2026-04-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='nidentificacion',
            new_name='identificacion',
        ),
        migrations.AddField(
            model_name='candidato',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Elegible', 'Elegible'), ('En Cartera', 'En Cartera'), ('No Elegible', 'No Elegible')], db_column='estatus', default='Pendiente', max_length=20),
        ),
    ]
