# Generated by Django 6.0.4 on 2026-04-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0002_rename_nidentificacion_candidato_identificacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='identificacion',
            new_name='cedula',
        ),
    ]
