# Generated by Django 6.0.4 on 2026-04-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0002_alter_candidato_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='disponibilidad',
            field=models.CharField(choices=[('Inmediata', 'Inmediata'), ('15 días', '15 días'), ('30 días', '30 días'), ('Remoto', 'Remoto'), ('Presencial', 'Presencial'), ('Híbrido', 'Híbrido'), ('Negociable', 'Negociable')], db_column='disponibilidad', default='Inmediata', max_length=50),
        ),
    ]
