# Generated by Django 6.0.4 on 2026-04-20 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0003_alter_candidato_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevista',
            name='justificacion_dictamen',
            field=models.TextField(blank=True, help_text='Explique brevemente el porqué de su decisión', null=True),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='puntuacion_comunicacion',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='puntuacion_interes',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='puntuacion_tecnica',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
