# Generated by Django 6.0.4 on 2026-04-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0004_entrevista_justificacion_dictamen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Elegible', 'Elegible'), ('En Cartera', 'En Cartera'), ('No Elegible', 'No Elegible'), ('En Revision', 'En Revision')], db_column='estatus', default='Pendiente', max_length=20),
        ),
    ]
