# Generated by Django 6.0.4 on 2026-04-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0004_alter_candidato_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='moneda',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], db_column='moneda', default='USD', max_length=3),
        ),
    ]
