# Generated by Django 6.0.4 on 2026-04-29 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0005_alter_candidato_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cedula',
            field=models.CharField(db_column='numero_identificacion', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='La identificación debe comenzar con V o E seguido de 6 a 9 dígitos.', regex='^[VE]\\d{6,9}$')]),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nombre_completo',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='telefono',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener el formato +58 4XX XXXXXXX.', regex='^\\+58\\s4\\d{9}$')]),
        ),
    ]
