# Generated by Django 6.0.4 on 2026-05-06 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0006_alter_candidato_cedula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Elegible', 'Elegible'), ('En Cartera', 'En Cartera'), ('No Elegible', 'No Elegible'), ('En Revision', 'En Revision'), ('Contratado', 'Contratado')], db_column='estatus', default='Pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('salario_acordado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda_salario', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area_definitiva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talento.area')),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contratacion_activa', to='talento.candidato')),
                ('procesado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contrataciones',
            },
        ),
    ]
