# Generated by Django 6.0.4 on 2026-05-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0007_alter_candidato_estatus_contratacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevista',
            name='eligibilidad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
