# Generated by Django 6.0.4 on 2026-05-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0008_alter_entrevista_eligibilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevista',
            name='fecha_programada',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora programada por RRHH', null=True),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='fecha_entrevista',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora real de finalización', null=True),
        ),
    ]
