# Generated by Django 6.0.4 on 2026-05-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0009_entrevista_fecha_programada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='especialidad_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='talento.especialidad'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Elegible', 'Elegible'), ('En Cartera', 'En Cartera'), ('No Elegible', 'No Elegible'), ('En Revision', 'En Revision')], db_column='estatus', default='Pendiente', max_length=20),
        ),
    ]
