# Generated by Django 6.0.4 on 2026-05-06 18:48

import django.core.validators
import talento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento', '0010_contratacion_especialidad_asignada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='url_documento_id',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='url_referencias',
        ),
        migrations.AddField(
            model_name='candidato',
            name='curriculum_vitae',
            field=models.FileField(blank=True, null=True, upload_to=talento.models.ruta_documentos_candidato, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='candidato',
            name='documento_identidad',
            field=models.FileField(blank=True, null=True, upload_to=talento.models.ruta_documentos_candidato, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='candidato',
            name='referencias',
            field=models.FileField(blank=True, null=True, upload_to=talento.models.ruta_documentos_candidato, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
